# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: dockertest
    steps:
    - task: Docker@2  
      inputs:  
        containerRegistry: 'TestDocker'  
        command: 'login'  
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: Docker@2  
      inputs:  
        containerRegistry: 'TestDocker'  
        repository: '$(Build.Repository.Name)'  
        command: 'push'